/**
 * Created by uvillazon on 04/09/2015.
 */
Ext.define('App.Model.Proformas.Modelos', {
    extend: 'Ext.data.Model',
    fields: [
        {type: "string", name: "MODELO"},
        {type: "string", name: "MATERIAL"},
        {type: "string", name: "COLOR"},
        {type: "string", name: "ITEM"},
        {type: "string", name: "VENDEDOR"},
        {type: "string", name: "CLIENTE"},
        {type: "string", name: "TALLA"},
        {type: "float", name: "CAJAS"},
        {type: "float", name: "PRECIO_VENTA"},
        {type: "float", name: "PRECIO_UNITARIO"},
        {type: "float", name: "1"},
        {type: "float", name: "1m"},
        {type: "float", name: "2"},
        {type: "float", name: "2m"},
        {type: "float", name: "3"},
        {type: "float", name: "3m"},
        {type: "float", name: "4"},
        {type: "float", name: "4m"},
        {type: "float", name: "5"},
        {type: "float", name: "5m"},
        {type: "float", name: "6"},
        {type: "float", name: "6m"},
        {type: "float", name: "7"},
        {type: "float", name: "7m"},
        {type: "float", name: "8"},
        {type: "float", name: "8m"},
        {type: "float", name: "9"},
        {type: "float", name: "9m"},
        {type: "float", name: "10"},
        {type: "float", name: "10m"},
        {type: "float", name: "11"},
        {type: "float", name: "11m"},
        {type: "float", name: "12"},
        {type: "float", name: "12m"},
        {type: "float", name: "13"},
        {type: "float", name: "13m"},
        {type: "float", name: "14"},
        {type: "float", name: "15"},
        {type: "float", name: "16"},
        {type: "float", name: "17"},
        {type: "float", name: "18"},
        {type: "float", name: "19"},
        {type: "float", name: "20"},
        {type: "float", name: "21"},
        {type: "float", name: "22"},
        {type: "float", name: "23"},
        {type: "float", name: "24"},
        {type: "float", name: "25"},
        {type: "float", name: "26"},
        {type: "float", name: "27"},
        {type: "float", name: "28"},
        {type: "float", name: "29"},
        {type: "float", name: "30"},
        {type: "float", name: "31"},
        {type: "float", name: "32"},
        {type: "float", name: "33"},
        {type: "float", name: "34"},
        {type: "float", name: "35"},
        {type: "float", name: "36"},
        {type: "float", name: "37"},
        {type: "float", name: "38"},
        {type: "float", name: "39"},
        {type: "float", name: "40"},
        {type: "float", name: "41"},
        {type: "float", name: "42"},
        {type: "float", name: "43"},
        {type: "float", name: "44"},
        {type: "float", name: "45"},
        {type: "float", name: "PARES"},
        {type: "float", name: "TOTAL"},
        {type: "string", name: "ESTADO"},
        {type: "float", name: "fila"}


    ]
});